name: BudgetPlanner
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.damytheknightking.budgetplanner.local
    DEVELOPMENT_TEAM: 954H68SH4A
    CODE_SIGN_STYLE: Automatic
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_VERSION: 5.10
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_CFBundleDisplayName: Budget Planner
targets:
  BudgetPlanner:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
    settings:
      base:
        PRODUCT_NAME: BudgetPlanner
        DEVELOPMENT_TEAM: 954H68SH4A
        CODE_SIGN_STYLE: Automatic
        PROVISIONING_PROFILE_SPECIFIER: ""
    dependencies: []
  BudgetPlannerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/BudgetPlannerTests
    dependencies:
      - target: BudgetPlanner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.damytheknightking.budgetplanner.local.tests
        GENERATE_INFOPLIST_FILE: YES
schemes:
  BudgetPlanner:
    build:
      targets:
        BudgetPlanner: all
        BudgetPlannerTests: [test]
    test:
      targets:
        - BudgetPlannerTests
